freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-1-release-amd64
  stateful: false
  setup_script:
    - pkg install -y curl zip cmake qt5-x11extras qt5-qmake qt5-widgets qt5-buildtools kf5-kdbusaddons kf5-kwindowsystem libdbusmenu-qt5
  test_script:
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j$(sysctl -n hw.ncpu)
    - make DESTDIR=Menubar.AppDir -j$(sysctl -n hw.ncpu) install
    - ( cd Filer.AppDir/ ; ln -s ./usr/bin/panda-statusbar ./AppRun )
    - rm -rf Menubar.AppDir/usr/include
    - find Menubar.AppDir/
    - zip --symlinks -r Menubar_FreeBSD.zip Menubar.AppDir/
    - curl --upload-file ./Menubar_FreeBSD.zip https://transfer.sh/Menubar_FreeBSD.zip
  only_if: $CIRRUS_BRANCH == 'actionsearch'
